services:
  flask:
    build: ./.docker/flask
    volumes:
      - ./app:/app
      - ./morse-frontend/public:/app/static
    ports:
      - '5000:5000'
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: app.py
