services:

  #Flask service
  flask:
    build: 
      context: .
      dockerfile: ./docker/nginx-uwsgi-flask/Dockerfile.prod
    ports:
      - 5000:80
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      #database configuration
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      #pusher configuration
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_KEY: ${PUSHER_KEY}
      PUSHER_SECRET: ${PUSHER_SECRET}
      #PUSHER_HOST: http://127.0.0.1
      #PUSHER_PORT: 9090
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}

  #MariaDb Service
  mariadb:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      MARIADB_PORT_NUMBER: 3306
    volumes:
      - morsechatdb:/bitnami/mariadb/data

# Volumes
volumes:
  morsechatdb:
