services:

  #Flask service
  flask:
    build:
      context: ./docker/nginx-uwsgi-flask
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/backend
    ports:
      - 5000:80
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      #database configuration
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      #pusher configuration
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_KEY: ${PUSHER_KEY}
      PUSHER_SECRET: ${PUSHER_SECRET}
      PUSHER_HOST: soketi #when self hosting, this is the internal resource
      PUSHER_HOST_WEB: localhost #when self hosting, this is the host url
      PUSHER_PORT: 6001
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}

  #MariaDb Service
  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      MARIADB_PORT_NUMBER: 3306
    volumes:
      - ./docker/mariadb/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      - ./docker/mariadb/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - morsechatdb:/bitnami/mariadb/data

  #Soketi service
  soketi:
    image: "quay.io/soketi/soketi:89604f268623cf799573178a7ba56b7491416bde-16-debian"
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      DEBUG: 1
      DEFAULT_APP_ID: ${PUSHER_APP_ID}
      DEFAULT_APP_KEY: ${PUSHER_KEY}
      DEFAULT_APP_SECRET: ${PUSHER_SECRET}

    volumes:
      - ./soketi-config.json:/opt/soketi/soketi-config.json:ro
    command:
      - "--config=/opt/soketi/soketi-config.json"

# Volumes
volumes:
  morsechatdb:
