services:

  #Flask service
  flask:
    build: 
      context: .
      dockerfile: ./docker/nginx-uwsgi-flask/Dockerfile.prod
    ports:
      - 5000:80
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      #database configuration
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      #pusher configuration
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_KEY: ${PUSHER_KEY}
      PUSHER_SECRET: ${PUSHER_SECRET}
      PUSHER_HOST: 127.0.0.1 #TODO: in production this must be halb.it
      PUSHER_HOST_INTERNAL: soketi #TODO: when self hosting in localost, this is necessary
      PUSHER_PORT: 6001
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}

  #MariaDb Service
  mariadb:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      MARIADB_PORT_NUMBER: 3306
    volumes:
      - morsechatdb:/bitnami/mariadb/data

  #Soketi service
  soketi:
    image: "quay.io/soketi/soketi:0.17-16-alpine"
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      DEBUG: 1
      DEFAULT_APP_ID: ${PUSHER_APP_ID}
      DEFAULT_APP_KEY: ${PUSHER_KEY}
      DEFAULT_APP_SECRET: ${PUSHER_SECRET}

# Volumes
volumes:
  morsechatdb:
