apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask
  namespace: morse
  labels:
    app: nginx-flask
spec:
  selector:
    matchLabels:
      app: nginx-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-flask
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx-flask
          image: ghcr.io/robalb/morsechat:sha-2fabfdd506096b15a03f4e0938c6c140ccfde49e
          env:
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_USER
              value: morse_prod
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: morse-secrets
                  key: MARIADB_PASSWORD
            - name: MARIADB_DATABASE
              value: morsechat
            - name: PUSHER_APP_ID
              valueFrom:
                secretKeyRef:
                  name: morse-secrets
                  key: PUSHER_APP_ID
            - name: PUSHER_KEY
              valueFrom:
                secretKeyRef:
                  name: morse-secrets
                  key: PUSHER_KEY
            - name: PUSHER_SECRET
              valueFrom:
                secretKeyRef:
                  name: morse-secrets
                  key: PUSHER_SECRET
            - name: PUSHER_CLUSTER
              value: eu
          ports:
            - containerPort: 80
