apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask
  namespace: morse
  labels:
    app: nginx-flask
spec:
  selector:
    matchLabels:
      app: nginx-flask
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx-flask
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx-flask
          image: ghcr.io/robalb/morsechat:sha-7085b3b7d35c97d77e4fff2f4fd1935202beb0ba
          env:
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_USER
              value: morse_prod
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: morse-secrets
                  key: MARIADB_PASSWORD
            - name: MARIADB_DATABASE
              value: morsechat
            - name: PUSHER_APP_ID
              value: '123456'
            - name: PUSHER_KEY
              value: tomanage-key
            - name: PUSHER_SECRET
              value: tomanage-secret
            - name: PUSHER_CLUSTER
              value: eu
            - name: PUSHER_HOST
              value: soketi
            - name: PUSHER_HOST_WEB
              value: soketi.halb.it
            - name: PUSHER_PORT
              value: '80'
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - curl
                - '-X POST'
                - http://localhost/api/v1/page_init?k8s-liveness-probe
            timeoutSeconds: 2
            initialDelaySeconds: 5
            periodSeconds: 60
